apiVersion: v1
kind: Service
metadata:
  name: toycluster-head-service
spec:
  type: NodePort
  selector:
    cluster.ray.io/component: toy-cluster-ray-head 
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 10001
      targetPort: 10001
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32703
